# This workflow will build kbs project

name: kbs-app-build

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "apps/kbs/**"
      - ".github/workflows/kbs-app-quality.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Versioning
      run: |
        echo "NEW_VERSION=$(cat ./apps/kbs/VERSION)" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USER }}/kbs
        tags: |
          type=raw,value=${{ NEW_VERSION }}

    - name: Build and push Docker image
      env:
        SHORT_SHA: ${GITHUB_SHA::8}
      uses: docker/build-push-action@v5
      with:
        context: ./apps/kbs
        push: true
        build-args: |
          "appVersion=${SHORT_SHA}"
          "commitHash=${GITHUB_SHA}"
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}